name: pinn_py311
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - tensorflow>=2.15.0,<2.16.0
  - numpy>=1.24.0,<1.26.0
  - scipy>=1.11.0,<1.12.0
  - scikit-learn>=1.3.0,<1.4.0
  - matplotlib>=3.7.0,<3.8.0
  - seaborn>=0.12.0,<0.13.0
  - pandas>=2.0.0,<2.1.0
  - jupyter>=1.0.0
  - ipykernel>=6.25.0
  - pip
  - pip:
      - sciann>=0.7.0
      - optuna>=3.4.0
      - ray[tune]>=2.7.0

# Pacotes via Conda‑Forge
  - deepxde
  - kagglehub
